name: Get Request for feliks

on:
  schedule:
    # Execute 10 mins
    - cron: '*/10 * * * *'

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
    - name: Make GET request
      run: |
        curl -X GET https://little.feliksdudek791.workers.dev/
